version: "3.9"
services:
  # Infraestructure
  development-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "devpassword(!)001"
      ACCEPT_EULA: "Y"

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
  # Services
  canchas:
    image: tenisapp.canchas.application:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development